"""
╔══════════════════════════════════════════════════════════════════════════════╗
║       CopaVision AI  |  Phase 2: Player Performance Intelligence            ║
║       Streamlit Dashboard — Production Ready                                ║
╚══════════════════════════════════════════════════════════════════════════════╝

Save this file as:  pages/02_Player_Dashboard.py

Data files expected (relative to app root):
    data/player_stats.csv
    data/player_per90.csv
    data/similarity_features.csv
    data/clustered_player_features.csv   ← generated by build_clusters() if missing
"""

# ─────────────────────────────────────────────────────────────────────────────
# IMPORTS
# ─────────────────────────────────────────────────────────────────────────────
import warnings
warnings.filterwarnings("ignore")

import json
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler
import streamlit as st

# ─────────────────────────────────────────────────────────────────────────────
# PAGE CONFIG
# ─────────────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Player Intelligence | CopaVision AI",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─────────────────────────────────────────────────────────────────────────────
# THEME — identical dark football palette as Phase 1
# ─────────────────────────────────────────────────────────────────────────────
CUSTOM_CSS = """
<style>
@import url('https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;600;700;900&family=DM+Sans:wght@300;400;500;600&display=swap');

:root {
    --bg-deep:  #050b14; --bg-card: #0e1621; --bg-panel: #121d2e;
    --border:   #1e3050; --accent: #00d4ff;  --accent2:  #00ff9d;
    --accent3:  #ff6b35; --gold:   #ffd700;  --text:     #e8f1ff;
    --muted:    #5a7a9a; --win:    #00ff9d;  --loss:     #ff4560;
    --draw:     #00d4ff;
}
.stApp {
    background-color: var(--bg-deep);
    background-image:
        radial-gradient(ellipse at 15% 0%,  rgba(0,212,255,0.06) 0%, transparent 50%),
        radial-gradient(ellipse at 85% 100%, rgba(0,255,157,0.04) 0%, transparent 50%);
    font-family: 'DM Sans', sans-serif;
    color: var(--text);
}
#MainMenu, footer, header {visibility: hidden;}
.block-container {padding-top: 1.5rem; padding-bottom: 2rem;}

[data-testid="stSidebar"] {
    background: var(--bg-panel) !important;
    border-right: 1px solid var(--border) !important;
}
[data-testid="stSidebar"] * {color: var(--text) !important;}

[data-testid="stMetric"] {
    background: var(--bg-card); border: 1px solid var(--border);
    border-radius: 12px; padding: 16px 20px !important;
}
[data-testid="stMetricValue"] {
    font-family: 'Barlow Condensed', sans-serif !important;
    font-size: 1.9rem !important; font-weight: 700 !important;
    color: var(--accent) !important;
}
[data-testid="stMetricLabel"] {color: var(--muted) !important; font-size: 0.75rem !important;}
[data-testid="stMetricDelta"] {font-size: 0.78rem !important;}

[data-testid="stSelectbox"] > div > div {
    background: var(--bg-card) !important; border: 1px solid var(--border) !important;
    border-radius: 8px !important; color: var(--text) !important;
}
.stButton > button {
    background: linear-gradient(135deg, #00d4ff 0%, #0099cc 100%);
    color: #050b14 !important; border: none !important; border-radius: 8px !important;
    font-family: 'Barlow Condensed', sans-serif !important; font-size: 1.05rem !important;
    font-weight: 700 !important; letter-spacing: 1px !important;
    padding: 0.5rem 1.6rem !important; transition: all 0.2s !important;
    text-transform: uppercase !important;
}
.stButton > button:hover {
    transform: translateY(-2px) !important;
    box-shadow: 0 6px 24px rgba(0,212,255,0.3) !important;
}
[data-testid="stTab"] {
    font-family: 'Barlow Condensed', sans-serif !important;
    font-size: 1rem !important; letter-spacing: 0.5px; color: var(--muted) !important;
}
[data-testid="stTab"][aria-selected="true"] {color: var(--accent) !important;}
[data-testid="stExpander"] {
    background: var(--bg-card) !important; border: 1px solid var(--border) !important;
    border-radius: 10px !important;
}
hr {border-color: var(--border) !important; margin: 1.2rem 0 !important;}
.stAlert {background: var(--bg-card) !important; border-radius: 10px !important;}
.stSpinner > div {border-top-color: var(--accent) !important;}

/* Custom card classes */
.cv-card {background:var(--bg-card);border:1px solid var(--border);border-radius:14px;padding:1.3rem 1.5rem;margin-bottom:0.9rem;}
.cv-card-accent {border-left:3px solid var(--accent);}
.cv-card-green  {border-left:3px solid var(--accent2);}
.cv-card-orange {border-left:3px solid var(--accent3);}
.cv-card-gold   {border-left:3px solid var(--gold);}
.cv-heading {font-family:'Barlow Condensed',sans-serif;font-size:1.6rem;font-weight:700;letter-spacing:1px;color:var(--text);text-transform:uppercase;margin-bottom:0.3rem;}
.cv-subheading {font-family:'Barlow Condensed',sans-serif;font-size:1rem;color:var(--muted);letter-spacing:0.5px;margin-bottom:1.1rem;}
.cv-label {font-family:'Barlow Condensed',sans-serif;font-size:0.72rem;color:#5a7a9a;letter-spacing:2.5px;text-transform:uppercase;margin-bottom:0.4rem;}

/* Player profile badge */
.player-badge {
    background: linear-gradient(135deg, var(--bg-card) 0%, #0a1828 100%);
    border: 1px solid var(--border); border-left: 4px solid var(--accent);
    border-radius: 14px; padding: 1.5rem 1.8rem; margin-bottom: 1rem;
}
.player-name {font-family:'Barlow Condensed',sans-serif;font-size:2rem;font-weight:900;color:var(--text);letter-spacing:1px;}
.player-sub  {font-family:'DM Sans',sans-serif;font-size:0.88rem;color:var(--muted);margin-top:0.2rem;}

/* Percentile bar */
.pct-bar-wrap {margin:4px 0;}
.pct-bar-label {font-size:0.8rem;color:var(--muted);margin-bottom:2px;}
.pct-bar-track {background:#1e3050;border-radius:4px;height:8px;width:100%;position:relative;}
.pct-bar-fill  {height:8px;border-radius:4px;position:absolute;top:0;left:0;}

/* Similarity badge */
.sim-badge {display:inline-block;font-family:'Barlow Condensed',sans-serif;
    font-size:0.85rem;font-weight:700;padding:3px 10px;border-radius:20px;
    background:rgba(0,212,255,0.12);border:1px solid rgba(0,212,255,0.3);
    color:#00d4ff;margin-left:8px;}

/* Archetype chip */
.archetype-chip {display:inline-block;font-family:'Barlow Condensed',sans-serif;
    font-size:1rem;font-weight:700;letter-spacing:1px;text-transform:uppercase;
    padding:6px 16px;border-radius:6px;margin:4px 4px 4px 0;}
</style>
"""
st.markdown(CUSTOM_CSS, unsafe_allow_html=True)

# ─────────────────────────────────────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────────────────────────────────────
DATA_DIR = Path(__file__).parent.parent / "data"

COLORS = {
    "accent":  "#00d4ff", "green":   "#00ff9d", "orange":  "#ff6b35",
    "gold":    "#ffd700", "purple":  "#d2a8ff", "muted":   "#5a7a9a",
    "bg":      "#0e1621", "panel":   "#121d2e", "border":  "#1e3050",
    "text":    "#e8f1ff",
}

POSITION_GROUPS = {
    "Goalkeeper": ["Goalkeeper"],
    "Defender": ["Center Back","Left Back","Right Back","Left Center Back",
                 "Right Center Back","Left Wing Back","Right Wing Back"],
    "Midfielder": ["Center Midfield","Left Center Midfield","Right Center Midfield",
                   "Center Defensive Midfield","Left Defensive Midfield","Right Defensive Midfield",
                   "Left Midfield","Right Midfield"],
    "Attacking Mid / Winger": ["Center Attacking Midfield","Left Attacking Midfield",
                                "Right Attacking Midfield","Left Wing","Right Wing"],
    "Forward": ["Center Forward","Left Center Forward","Right Center Forward","Secondary Striker"],
}

# Cluster archetype definitions (tuned per KMeans output order)
CLUSTER_ARCHETYPES = {
    0: {"name": "Defensive Anchor",    "color": "#ff6b35", "icon": "🛡️",
        "desc": "Strong tackling, aerial dominance, high pressure work-rate. The backbone of defensive shape."},
    1: {"name": "Ball Winner",         "color": "#d2a8ff", "icon": "⚔️",
        "desc": "High duel success, interceptions, and pressure intensity. Wins the ball back in transition."},
    2: {"name": "Deep-Lying Playmaker","color": "#00d4ff", "icon": "🎯",
        "desc": "Elite passing volume, progressive passes, high accuracy. Dictates tempo from deep."},
    3: {"name": "Clinical Finisher",   "color": "#ffd700", "icon": "⚡",
        "desc": "High xG, shots on target, excellent conversion rate. Lives inside the penalty box."},
    4: {"name": "Box-to-Box Engine",   "color": "#00ff9d", "icon": "🔄",
        "desc": "Balanced across attack and defence. High work-rate, carries, and progressive actions."},
    5: {"name": "Creative Winger",     "color": "#ff6b35", "icon": "🌪️",
        "desc": "Elite dribbling, carries, and assists. Creates chances through direct 1v1 actions."},
    6: {"name": "High Press Striker",  "color": "#ffd700", "icon": "🎯",
        "desc": "Goals, pressures, and duels in the final third. Terrorises defences with movement."},
    7: {"name": "Possession Carrier",  "color": "#00d4ff", "icon": "🎪",
        "desc": "Progressive carries, dribble success, and creative passing. Drives forward with the ball."},
}

RADAR_METRICS = {
    "Attacking":   ["goals_per90", "shots_per90", "xg_per90", "shot_accuracy"],
    "Creating":    ["assists_per90", "xassists_per90", "progressive_passes_per90", "dribbles_completed_per90"],
    "Defending":   ["tackles_per90", "interceptions_per90", "pressures_per90", "clearances_per90"],
    "Possession":  ["passes_completed_per90", "pass_accuracy", "carries_per90", "dribble_success_rate"],
    "Physicality": ["duels_per90", "aerial_duels_per90", "fouls_won_per90", "duel_success_rate"],
}

FEATURE_COLS_SIM = [c for c in [
    "goals_per90_scaled","assists_per90_scaled","shots_per90_scaled",
    "shots_on_target_per90_scaled","xg_per90_scaled",
    "passes_attempted_per90_scaled","passes_completed_per90_scaled",
    "progressive_passes_per90_scaled","dribbles_attempted_per90_scaled",
    "dribbles_completed_per90_scaled","carries_per90_scaled",
    "tackles_per90_scaled","tackles_won_per90_scaled","interceptions_per90_scaled",
    "pressures_per90_scaled","aerial_duels_per90_scaled","aerial_duels_won_per90_scaled",
    "duels_per90_scaled","duels_won_per90_scaled","pass_accuracy_scaled",
    "dribble_success_rate_scaled","tackle_success_rate_scaled",
    "aerial_success_rate_scaled","duel_success_rate_scaled",
]]

MIN_MINUTES = 450  # minimum minutes played for meaningful stats

# ─────────────────────────────────────────────────────────────────────────────
# DATA LOADING & CACHING
# ─────────────────────────────────────────────────────────────────────────────
@st.cache_data(show_spinner=False)
def load_player_stats() -> pd.DataFrame:
    df = pd.read_csv(DATA_DIR / "player_stats.csv")
    df["position_group"] = df["position"].apply(_map_position_group)
    df["display_name"] = df["player_nickname"].fillna(df["player_name"])
    df = df[df["position"] != "0"]  # drop invalid rows
    return df

@st.cache_data(show_spinner=False)
def load_player_per90() -> pd.DataFrame:
    df = pd.read_csv(DATA_DIR / "player_per90.csv")
    df["display_name"] = df["player_nickname"].fillna(df["player_name"])
    df = df[df["position"] != "0"]
    return df

@st.cache_data(show_spinner=False)
def load_similarity_features() -> pd.DataFrame:
    return pd.read_csv(DATA_DIR / "similarity_features.csv").fillna(0)

@st.cache_data(show_spinner=False)
def load_clustered_features() -> pd.DataFrame:
    """
    Load or generate clustered player features.
    If the CSV is missing the required 'cluster' column it is rebuilt
    automatically from similarity_features.csv.
    """
    REQUIRED = {"player_id", "cluster", "pca_x", "pca_y", "tsne_x", "tsne_y"}
    cluster_path = DATA_DIR / "clustered_player_features.csv"
    if cluster_path.exists():
        df = pd.read_csv(cluster_path)
        if REQUIRED.issubset(set(df.columns)):
            return df
        # File exists but columns are wrong — fall through to rebuild
    return _build_clusters()


@st.cache_data(show_spinner=False)
def _build_clusters() -> pd.DataFrame:
    """Compute KMeans clusters + PCA + t-SNE from similarity features."""
    sim = load_similarity_features()
    X = sim[FEATURE_COLS_SIM].values

    km = KMeans(n_clusters=8, random_state=42, n_init=10)
    clusters = km.fit_predict(X)

    pca = PCA(n_components=2, random_state=42)
    pca_coords = pca.fit_transform(X)

    # Note: n_jobs not supported on all platforms — omit for portability
    tsne = TSNE(n_components=2, random_state=42, perplexity=30)
    tsne_coords = tsne.fit_transform(X)

    df = sim[["player_id", "player_name", "primary_position",
              "team_name", "competition_name"]].copy()
    df["cluster"] = clusters
    df["pca_x"]   = pca_coords[:, 0]
    df["pca_y"]   = pca_coords[:, 1]
    df["tsne_x"]  = tsne_coords[:, 0]
    df["tsne_y"]  = tsne_coords[:, 1]

    # Persist so next app restart skips this computation
    try:
        (DATA_DIR / "clustered_player_features.csv").write_text(
            df.to_csv(index=False), encoding="utf-8"
        )
    except Exception:
        pass  # Read-only FS (e.g. Streamlit Cloud) — silently skip
    return df

def _map_position_group(pos: str) -> str:
    for group, positions in POSITION_GROUPS.items():
        if pos in positions:
            return group
    return "Other"

# ─────────────────────────────────────────────────────────────────────────────
# UTILITY FUNCTIONS
# ─────────────────────────────────────────────────────────────────────────────
def percentile_rank(series: pd.Series, value: float) -> float:
    """Compute percentile of a value within a series (0–100)."""
    if series.std() == 0:
        return 50.0
    return float((series < value).mean() * 100)


def get_percentile_color(pct: float) -> str:
    if pct >= 80: return COLORS["green"]
    if pct >= 60: return COLORS["accent"]
    if pct >= 40: return COLORS["gold"]
    return COLORS["orange"]


def pct_bar_html(label: str, pct: float, val: str = "") -> str:
    color = get_percentile_color(pct)
    return f"""
    <div class="pct-bar-wrap">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:3px;">
            <span style="font-size:0.82rem;color:{COLORS['muted']};">{label}</span>
            <span style="font-size:0.82rem;color:{COLORS['text']};font-weight:600;">{val}
                <span style="color:{color};font-size:0.75rem;"> ({pct:.0f}th)</span>
            </span>
        </div>
        <div class="pct-bar-track">
            <div class="pct-bar-fill" style="width:{min(pct,100):.0f}%;background:{color};"></div>
        </div>
    </div>"""


def stat_row_html(label: str, val, color: str = "#e8f1ff") -> str:
    return (f'<div style="display:flex;justify-content:space-between;padding:4px 0;'
            f'border-bottom:1px solid #1e3050;">'
            f'<span style="color:{COLORS["muted"]};font-size:0.85rem;">{label}</span>'
            f'<span style="color:{color};font-weight:600;font-size:0.85rem;">{val}</span></div>')


def cv_section(title: str, subtitle: str = ""):
    st.markdown(f'<div class="cv-heading">{title}</div>', unsafe_allow_html=True)
    if subtitle:
        st.markdown(f'<div class="cv-subheading">{subtitle}</div>', unsafe_allow_html=True)


def _fmt(val, decimals=2):
    if pd.isna(val): return "—"
    if isinstance(val, float): return f"{val:.{decimals}f}"
    return str(val)


# ─────────────────────────────────────────────────────────────────────────────
# PLOTLY CHART BUILDERS
# ─────────────────────────────────────────────────────────────────────────────
_PLOT_LAYOUT = dict(
    template="plotly_dark",
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
)

def make_radar(player_row: pd.Series, reference_row: pd.Series,
               player_name: str, ref_name: str,
               per90_df: pd.DataFrame) -> go.Figure:
    """Spider/radar chart comparing two players across metric groups."""
    labels, p_vals, r_vals = [], [], []

    for group, metrics in RADAR_METRICS.items():
        for m in metrics:
            col = m if m in per90_df.columns else None
            if col is None: continue
            labels.append(m.replace("_per90","").replace("_"," ").title())
            p_vals.append(percentile_rank(per90_df[col].dropna(), player_row.get(col, 0)))
            r_vals.append(percentile_rank(per90_df[col].dropna(), reference_row.get(col, 0)))

    fig = go.Figure()
    for name, vals, color, alpha in [
        (player_name, p_vals, COLORS["green"],  "33"),
        (ref_name,    r_vals, COLORS["accent"], "22"),
    ]:
        fig.add_trace(go.Scatterpolar(
            r=vals + [vals[0]], theta=labels + [labels[0]],
            fill="toself",
            fillcolor=color + alpha,
            line=dict(color=color, width=2),
            name=name,
            hovertemplate="<b>%{theta}</b><br>Percentile: %{r:.0f}<extra></extra>",
        ))

    fig.update_layout(
        **_PLOT_LAYOUT,
        polar=dict(
            bgcolor="rgba(14,22,33,0.6)",
            radialaxis=dict(visible=True, range=[0,100], showticklabels=False,
                            gridcolor=COLORS["border"]),
            angularaxis=dict(tickfont=dict(family="DM Sans", size=10, color=COLORS["text"]),
                             gridcolor=COLORS["border"]),
        ),
        legend=dict(font=dict(family="Barlow Condensed", color=COLORS["text"], size=13),
                    bgcolor="rgba(0,0,0,0)"),
        height=440, margin=dict(t=40, b=40, l=40, r=40),
    )
    return fig


def make_percentile_bars(player_row: pd.Series, per90_df: pd.DataFrame,
                          player_name: str) -> go.Figure:
    """Horizontal percentile bar chart for a single player."""
    metrics = {
        "Goals p90": "goals_per90", "Assists p90": "assists_per90",
        "xG p90": "xg_per90", "xA p90": "xassists_per90",
        "Prog. Passes p90": "progressive_passes_per90",
        "Dribbles p90": "dribbles_completed_per90",
        "Tackles p90": "tackles_per90", "Interceptions p90": "interceptions_per90",
        "Pressures p90": "pressures_per90", "Pass Accuracy": "pass_accuracy",
    }
    labels, pcts = [], []
    for label, col in metrics.items():
        if col in per90_df.columns and col in player_row.index:
            pct = percentile_rank(per90_df[col].dropna(), player_row.get(col, 0))
            labels.append(label); pcts.append(pct)

    colors = [get_percentile_color(p) for p in pcts]

    fig = go.Figure(go.Bar(
        x=pcts, y=labels, orientation="h",
        marker=dict(color=colors, line=dict(width=0)),
        text=[f"{p:.0f}th" for p in pcts], textposition="outside",
        textfont=dict(family="Barlow Condensed", size=12, color=COLORS["text"]),
        hovertemplate="<b>%{y}</b><br>Percentile: %{x:.0f}<extra></extra>",
    ))
    fig.update_layout(
        **_PLOT_LAYOUT,
        xaxis=dict(range=[0, 115], showgrid=False, visible=False),
        yaxis=dict(tickfont=dict(family="DM Sans", size=11, color=COLORS["text"])),
        height=380, margin=dict(t=10, b=10, l=10, r=60),
        title=dict(text=f"Percentile Rankings — {player_name}",
                   font=dict(family="Barlow Condensed", size=14, color=COLORS["text"])),
    )
    return fig


def make_comparison_bar(p1_row, p2_row, p1_name, p2_name, per90_df) -> go.Figure:
    """Grouped bar comparing two players' percentile ranks."""
    metrics = {
        "Goals": "goals_per90", "Assists": "assists_per90",
        "xG": "xg_per90", "Prog Passes": "progressive_passes_per90",
        "Dribbles": "dribbles_completed_per90", "Tackles": "tackles_per90",
        "Interceptions": "interceptions_per90", "Pass Acc.": "pass_accuracy",
        "Pressures": "pressures_per90",
    }
    labels, p1_vals, p2_vals = [], [], []
    for label, col in metrics.items():
        if col in per90_df.columns:
            labels.append(label)
            p1_vals.append(percentile_rank(per90_df[col].dropna(), p1_row.get(col, 0)))
            p2_vals.append(percentile_rank(per90_df[col].dropna(), p2_row.get(col, 0)))

    fig = go.Figure()
    fig.add_trace(go.Bar(name=p1_name, x=labels, y=p1_vals,
                         marker_color=COLORS["green"],
                         text=[f"{v:.0f}" for v in p1_vals], textposition="outside",
                         textfont=dict(size=10, color=COLORS["text"]),
                         hovertemplate="<b>%{x}</b><br>" + p1_name + ": %{y:.0f}th<extra></extra>"))
    fig.add_trace(go.Bar(name=p2_name, x=labels, y=p2_vals,
                         marker_color=COLORS["accent"],
                         text=[f"{v:.0f}" for v in p2_vals], textposition="outside",
                         textfont=dict(size=10, color=COLORS["text"]),
                         hovertemplate="<b>%{x}</b><br>" + p2_name + ": %{y:.0f}th<extra></extra>"))
    fig.update_layout(
        **_PLOT_LAYOUT, barmode="group",
        xaxis=dict(tickfont=dict(family="Barlow Condensed", size=11, color=COLORS["text"])),
        yaxis=dict(range=[0, 120], gridcolor=COLORS["border"],
                   title="Percentile Rank", titlefont=dict(color=COLORS["muted"])),
        legend=dict(font=dict(family="Barlow Condensed", color=COLORS["text"], size=13),
                    bgcolor="rgba(0,0,0,0)"),
        height=380, margin=dict(t=20, b=20, l=40, r=20),
    )
    return fig


def make_cluster_scatter(clustered_df: pd.DataFrame, highlight_id=None,
                          mode: str = "pca") -> go.Figure:
    """PCA or t-SNE cluster scatter plot."""
    x_col = "pca_x" if mode == "pca" else "tsne_x"
    y_col = "pca_y" if mode == "pca" else "tsne_y"

    fig = go.Figure()
    for cid, arch in CLUSTER_ARCHETYPES.items():
        sub = clustered_df[clustered_df["cluster"] == cid]
        fig.add_trace(go.Scatter(
            x=sub[x_col], y=sub[y_col],
            mode="markers", name=arch["name"],
            marker=dict(size=5, color=arch["color"], opacity=0.55,
                        line=dict(width=0)),
            text=sub["player_name"],
            customdata=sub[["primary_position","team_name"]].values,
            hovertemplate=(
                "<b>%{text}</b><br>%{customdata[0]}<br>%{customdata[1]}<br>"
                f"Archetype: {arch['name']}<extra></extra>"
            ),
        ))

    # Highlight selected player
    if highlight_id is not None:
        hi = clustered_df[clustered_df["player_id"] == highlight_id]
        if not hi.empty:
            fig.add_trace(go.Scatter(
                x=hi[x_col], y=hi[y_col], mode="markers+text",
                marker=dict(size=16, color=COLORS["gold"], symbol="star",
                            line=dict(color="white", width=1.5)),
                text=hi["player_name"], textposition="top center",
                textfont=dict(family="Barlow Condensed", size=12, color=COLORS["gold"]),
                name="Selected Player", showlegend=True,
                hovertemplate="<b>%{text}</b><br>★ Selected<extra></extra>",
            ))

    axis_title = "PCA Component" if mode == "pca" else "t-SNE Dimension"
    fig.update_layout(
        **_PLOT_LAYOUT,
        height=520,
        xaxis=dict(title=f"{axis_title} 1", showgrid=False,
                   tickfont=dict(color=COLORS["muted"])),
        yaxis=dict(title=f"{axis_title} 2", showgrid=False,
                   tickfont=dict(color=COLORS["muted"])),
        legend=dict(font=dict(family="Barlow Condensed", size=11, color=COLORS["text"]),
                    bgcolor="rgba(0,0,0,0)", orientation="v"),
        margin=dict(t=20, b=40, l=40, r=20),
        title=dict(text=f"Player Archetypes — {'PCA' if mode=='pca' else 't-SNE'} Projection",
                   font=dict(family="Barlow Condensed", size=14, color=COLORS["text"])),
    )
    return fig


def make_cluster_size_bar(clustered_df: pd.DataFrame) -> go.Figure:
    """Bar chart of player counts per archetype."""
    counts = clustered_df["cluster"].value_counts().sort_index()
    names  = [CLUSTER_ARCHETYPES[i]["name"] for i in counts.index]
    colors = [CLUSTER_ARCHETYPES[i]["color"] for i in counts.index]

    fig = go.Figure(go.Bar(
        x=names, y=counts.values,
        marker=dict(color=colors, line=dict(width=0)),
        text=counts.values, textposition="outside",
        textfont=dict(family="Barlow Condensed", size=12, color=COLORS["text"]),
        hovertemplate="<b>%{x}</b><br>Players: %{y}<extra></extra>",
    ))
    fig.update_layout(
        **_PLOT_LAYOUT, height=320,
        xaxis=dict(tickfont=dict(family="Barlow Condensed", size=10, color=COLORS["text"]),
                   tickangle=-20),
        yaxis=dict(showgrid=True, gridcolor=COLORS["border"],
                   tickfont=dict(color=COLORS["muted"])),
        margin=dict(t=20, b=80, l=40, r=20),
    )
    return fig


def make_similarity_heatmap(sim_matrix: np.ndarray, names: list) -> go.Figure:
    """Heatmap of cosine similarity between selected players."""
    fig = go.Figure(go.Heatmap(
        z=sim_matrix, x=names, y=names,
        colorscale=[[0, "#0e1621"],[0.5, "#1e3050"],[1, "#00d4ff"]],
        text=[[f"{v:.2f}" for v in row] for row in sim_matrix],
        texttemplate="%{text}", textfont=dict(size=11, color=COLORS["text"]),
        hovertemplate="<b>%{y}</b> × <b>%{x}</b><br>Similarity: %{z:.3f}<extra></extra>",
        showscale=True,
        colorbar=dict(tickfont=dict(color=COLORS["muted"])),
    ))
    fig.update_layout(
        **_PLOT_LAYOUT, height=420,
        xaxis=dict(tickangle=-30, tickfont=dict(family="DM Sans", size=10, color=COLORS["text"])),
        yaxis=dict(tickfont=dict(family="DM Sans", size=10, color=COLORS["text"])),
        margin=dict(t=20, b=80, l=100, r=20),
    )
    return fig


# ─────────────────────────────────────────────────────────────────────────────
# SIMILAR PLAYER ENGINE
# ─────────────────────────────────────────────────────────────────────────────
def find_similar_players(player_id: int, sim_df: pd.DataFrame,
                          n: int = 10, same_pos_only: bool = False) -> pd.DataFrame:
    """Return top-N most similar players using cosine similarity."""
    idx = sim_df.index[sim_df["player_id"] == player_id]
    if len(idx) == 0:
        return pd.DataFrame()

    pos = sim_df.loc[idx[0], "primary_position"]
    X = sim_df[FEATURE_COLS_SIM].values
    query_vec = X[idx[0]].reshape(1, -1)
    sims = cosine_similarity(query_vec, X)[0]

    result = sim_df.copy()
    result["similarity"] = sims
    result = result[result["player_id"] != player_id]

    if same_pos_only:
        result = result[result["primary_position"] == pos]

    return result.nlargest(n, "similarity")[
        ["player_id","player_name","primary_position","team_name",
         "competition_name","similarity"]
    ].reset_index(drop=True)


# ─────────────────────────────────────────────────────────────────────────────
# PLAYER PROFILE CARD
# ─────────────────────────────────────────────────────────────────────────────
def render_player_profile(player_row, per90_row, cluster_row, per90_df):
    """Full player profile: header card + metrics + percentiles."""
    # Safe cluster lookup — handles None and malformed rows
    arch = {}
    if cluster_row is not None:
        try:
            cid = int(cluster_row["cluster"])
            arch = CLUSTER_ARCHETYPES.get(cid, {})
        except (KeyError, ValueError, TypeError):
            arch = {}
    arch_color = arch.get("color", COLORS["accent"]) if arch else COLORS["accent"]
    arch_name  = arch.get("name", "Unknown") if arch else "Unknown"
    arch_icon  = arch.get("icon", "⚽") if arch else "⚽"

    # ── Header card ──────────────────────────────────────────────────────────
    st.markdown(f"""
    <div class="player-badge">
        <div style="display:flex;justify-content:space-between;align-items:flex-start;">
            <div>
                <div class="player-name">{player_row.get('display_name', player_row['player_name'])}</div>
                <div class="player-sub">
                    🏟️ <b style="color:{COLORS['text']};">{player_row['team']}</b>
                    &nbsp;·&nbsp; {player_row['position']}
                    &nbsp;·&nbsp; 🌍 {player_row.get('country','—')}
                    &nbsp;·&nbsp; 🏆 {player_row['competition']}
                </div>
            </div>
            <div style="text-align:right;">
                <span class="archetype-chip"
                    style="background:rgba(255,255,255,0.07);color:{arch_color};
                           border:1px solid {arch_color};">
                    {arch_icon} {arch_name}
                </span>
            </div>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Key metrics row ───────────────────────────────────────────────────────
    m1, m2, m3, m4, m5, m6 = st.columns(6)
    m1.metric("⚽ Goals",    _fmt(player_row.get("goals",0), 0))
    m2.metric("🎯 Assists",  _fmt(player_row.get("assists",0), 0))
    m3.metric("📈 xG",       _fmt(player_row.get("xg",0)))
    m4.metric("✨ xA",       _fmt(player_row.get("xassists",0)))
    m5.metric("⏱️ Minutes",  _fmt(player_row.get("minutes_played",0), 0))
    m6.metric("🏁 Matches",  _fmt(player_row.get("matches_played",0), 0))

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Tabs: Percentiles | Stats | Archetype ────────────────────────────────
    t1, t2, t3 = st.tabs(["📊 Percentile Rankings", "📋 Full Statistics", "🎭 Role Analysis"])

    with t1:
        c1, c2 = st.columns([3, 2])
        with c1:
            st.plotly_chart(make_percentile_bars(per90_row, per90_df, player_row['display_name']),
                            use_container_width=True, config={"displayModeBar": False})
        with c2:
            st.markdown("<br>", unsafe_allow_html=True)
            _render_strengths_weaknesses(per90_row, per90_df)

    with t2:
        _render_full_stats(player_row, per90_row)

    with t3:
        _render_role_analysis(player_row, per90_row, per90_df, arch, arch_color)


def _render_strengths_weaknesses(per90_row: pd.Series, per90_df: pd.DataFrame):
    """Top 3 strengths and bottom 3 weaknesses based on percentiles."""
    key_metrics = {
        "Goals/90": "goals_per90", "Assists/90": "assists_per90",
        "xG/90": "xg_per90", "Prog Passes/90": "progressive_passes_per90",
        "Dribbles/90": "dribbles_completed_per90", "Tackles/90": "tackles_per90",
        "Interceptions/90": "interceptions_per90", "Pressures/90": "pressures_per90",
        "Pass Accuracy": "pass_accuracy", "Aerial Duels/90": "aerial_duels_per90",
    }
    pcts = {}
    for label, col in key_metrics.items():
        if col in per90_df.columns and col in per90_row.index:
            pcts[label] = percentile_rank(per90_df[col].dropna(), per90_row.get(col, 0))

    sorted_pcts = sorted(pcts.items(), key=lambda x: x[1], reverse=True)
    strengths  = sorted_pcts[:3]
    weaknesses = sorted_pcts[-3:][::-1]

    st.markdown(f"""
    <div class="cv-card cv-card-green" style="margin-bottom:0.6rem;">
        <div class="cv-label">💪 Key Strengths</div>
        {''.join(f'<div style="display:flex;justify-content:space-between;padding:4px 0;">'
                 f'<span style="color:{COLORS["text"]};font-size:0.85rem;">✓ {l}</span>'
                 f'<span style="color:{COLORS["green"]};font-weight:700;font-size:0.85rem;">{p:.0f}th</span></div>'
                 for l, p in strengths)}
    </div>
    <div class="cv-card cv-card-orange">
        <div class="cv-label">⚠️ Relative Weaknesses</div>
        {''.join(f'<div style="display:flex;justify-content:space-between;padding:4px 0;">'
                 f'<span style="color:{COLORS["text"]};font-size:0.85rem;">△ {l}</span>'
                 f'<span style="color:{COLORS["orange"]};font-weight:700;font-size:0.85rem;">{p:.0f}th</span></div>'
                 for l, p in weaknesses)}
    </div>
    """, unsafe_allow_html=True)


def _render_full_stats(player_row: pd.Series, per90_row: pd.Series):
    c1, c2, c3 = st.columns(3)
    with c1:
        st.markdown(f"""<div class="cv-card cv-card-accent">
        <div class="cv-label">⚽ Attacking</div>
        {stat_row_html("Goals", _fmt(player_row.get("goals",0),0), COLORS["green"])}
        {stat_row_html("Shots", _fmt(player_row.get("shots",0),0))}
        {stat_row_html("Shots on Target", _fmt(player_row.get("shots_on_target",0),0))}
        {stat_row_html("xG", _fmt(player_row.get("xg",0)))}
        {stat_row_html("Goal Conv. Rate", _fmt(player_row.get("goal_conversion_rate",0))+"%")}
        {stat_row_html("Shot Accuracy", _fmt(player_row.get("shot_accuracy",0))+"%")}
        {stat_row_html("Goals / 90", _fmt(per90_row.get("goals_per90",0)), COLORS["green"])}
        {stat_row_html("xG / 90", _fmt(per90_row.get("xg_per90",0)))}
        </div>""", unsafe_allow_html=True)

    with c2:
        st.markdown(f"""<div class="cv-card cv-card-accent">
        <div class="cv-label">🎯 Creating & Passing</div>
        {stat_row_html("Assists", _fmt(player_row.get("assists",0),0), COLORS["accent"])}
        {stat_row_html("xA", _fmt(player_row.get("xassists",0)))}
        {stat_row_html("Passes Attempted", _fmt(player_row.get("passes_attempted",0),0))}
        {stat_row_html("Passes Completed", _fmt(player_row.get("passes_completed",0),0))}
        {stat_row_html("Pass Accuracy", _fmt(player_row.get("pass_accuracy",0))+"%")}
        {stat_row_html("Progressive Passes", _fmt(player_row.get("progressive_passes",0),0))}
        {stat_row_html("Dribbles (won/att)", f"{_fmt(player_row.get('dribbles_completed',0),0)}/{_fmt(player_row.get('dribbles_attempted',0),0)}")}
        {stat_row_html("Dribble Success", _fmt(player_row.get("dribble_success_rate",0))+"%")}
        </div>""", unsafe_allow_html=True)

    with c3:
        st.markdown(f"""<div class="cv-card cv-card-accent">
        <div class="cv-label">🛡️ Defending</div>
        {stat_row_html("Tackles", _fmt(player_row.get("tackles",0),0))}
        {stat_row_html("Tackles Won", _fmt(player_row.get("tackles_won",0),0))}
        {stat_row_html("Tackle Success", _fmt(player_row.get("tackle_success_rate",0))+"%")}
        {stat_row_html("Interceptions", _fmt(player_row.get("interceptions",0),0), COLORS["accent"])}
        {stat_row_html("Pressures", _fmt(player_row.get("pressures",0),0))}
        {stat_row_html("Clearances", _fmt(player_row.get("clearances",0),0))}
        {stat_row_html("Aerial Duels (won)", f"{_fmt(player_row.get('aerial_duels_won',0),0)}/{_fmt(player_row.get('aerial_duels',0),0)}")}
        {stat_row_html("Aerial Success", _fmt(player_row.get("aerial_success_rate",0))+"%")}
        </div>""", unsafe_allow_html=True)


def _render_role_analysis(player_row, per90_row, per90_df, arch, arch_color):
    """Narrative role breakdown with attacking/creative/defensive index bars."""
    # Compute three composite indices (0–100 scale via percentile)
    def composite(cols):
        scores = [percentile_rank(per90_df[c].dropna(), per90_row.get(c, 0))
                  for c in cols if c in per90_df.columns and c in per90_row.index]
        return np.mean(scores) if scores else 50.0

    att_idx = composite(["goals_per90", "shots_per90", "xg_per90", "shot_accuracy"])
    cre_idx = composite(["assists_per90", "progressive_passes_per90",
                          "dribbles_completed_per90", "pass_accuracy"])
    def_idx = composite(["tackles_per90", "interceptions_per90",
                          "pressures_per90", "clearances_per90"])

    pct_html = "".join([
        pct_bar_html("⚽ Attacking Index",   att_idx, f"{att_idx:.0f}"),
        pct_bar_html("🎨 Creative Index",    cre_idx, f"{cre_idx:.0f}"),
        pct_bar_html("🛡️ Defensive Index",  def_idx, f"{def_idx:.0f}"),
    ])

    desc = arch.get("desc", "Player role could not be determined.")
    icon = arch.get("icon","⚽")
    name = arch.get("name","Unknown")

    st.markdown(f"""
    <div class="cv-card cv-card-gold" style="margin-bottom:1rem;">
        <div class="cv-label">🎭 Player Archetype</div>
        <div style="display:flex;align-items:center;gap:12px;margin-bottom:0.8rem;">
            <span style="font-size:2rem;">{icon}</span>
            <span style="font-family:'Barlow Condensed',sans-serif;font-size:1.6rem;
                  font-weight:700;color:{arch_color};letter-spacing:1px;">{name}</span>
        </div>
        <p style="color:{COLORS['text']};font-size:0.9rem;line-height:1.6;">{desc}</p>
    </div>
    <div class="cv-card">
        <div class="cv-label">📊 Role Indices (Percentile vs. All Players)</div>
        {pct_html}
    </div>
    """, unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────────────────────
# SIDEBAR
# ─────────────────────────────────────────────────────────────────────────────
def render_sidebar():
    with st.sidebar:
        st.markdown("""
        <div style="text-align:center;padding:1rem 0 1.2rem;">
            <div style="font-family:'Barlow Condensed',sans-serif;font-size:1.9rem;
                 font-weight:900;color:#00d4ff;letter-spacing:3px;">
                 COPA<span style="color:#00ff9d;">VISION</span></div>
            <div style="font-family:'Barlow Condensed',sans-serif;font-size:0.8rem;
                 color:#5a7a9a;letter-spacing:4px;">A I  ·  P H A S E  2</div>
        </div><hr>""", unsafe_allow_html=True)

        st.markdown('<p class="cv-label">NAVIGATION</p>', unsafe_allow_html=True)
        page = st.radio("page", [
            "🔍  Player Search & Profile",
            "⚖️   Player Comparison",
            "🗺️   Cluster Explorer",
            "🔗  Similarity Engine",
        ], label_visibility="collapsed")

        st.markdown("<hr>", unsafe_allow_html=True)
        st.markdown('<p class="cv-label">PHASE ROADMAP</p>', unsafe_allow_html=True)
        st.markdown("""
        <div style="font-size:0.82rem;line-height:2.2;">
            <span style="color:#00ff9d;">✓</span> Phase 1 · Match Predictor<br>
            <span style="color:#00d4ff;">✓</span> Phase 2 · Player Intelligence<br>
            <span style="color:#5a7a9a;">○</span> Phase 3 · Sentiment Tracker<br>
            <span style="color:#5a7a9a;">○</span> Phase 4 · Live Match Feed
        </div>""", unsafe_allow_html=True)

    return page.split("  ")[-1].strip()


# ─────────────────────────────────────────────────────────────────────────────
# PAGE 1 — PLAYER SEARCH & PROFILE
# ─────────────────────────────────────────────────────────────────────────────
def page_player_profile(ps_df, pp_df, sim_df, cl_df):
    cv_section("🔍 Player Search & Profile",
               "Search any player, filter by position, competition, or team — then explore their complete intelligence report")
    st.markdown('<hr style="border-color:#1e3050;">', unsafe_allow_html=True)

    # ── Filter panel ──────────────────────────────────────────────────────────
    with st.expander("🎛️  Filters", expanded=True):
        f1, f2, f3, f4 = st.columns(4)
        with f1:
            st.markdown('<p class="cv-label">Position Group</p>', unsafe_allow_html=True)
            pos_filter = st.multiselect("pos", ["All"] + list(POSITION_GROUPS.keys()),
                                         default=["All"], label_visibility="collapsed")
        with f2:
            st.markdown('<p class="cv-label">Competition</p>', unsafe_allow_html=True)
            comps = ["All"] + sorted(ps_df["competition"].unique())
            comp_filter = st.selectbox("comp", comps, label_visibility="collapsed")
        with f3:
            st.markdown('<p class="cv-label">Team</p>', unsafe_allow_html=True)
            teams_avail = ["All"] + sorted(ps_df["team"].unique())
            team_filter = st.selectbox("team", teams_avail, label_visibility="collapsed")
        with f4:
            st.markdown('<p class="cv-label">Min. Minutes Played</p>', unsafe_allow_html=True)
            min_mins = st.slider("mins", 90, 5000, MIN_MINUTES, 90, label_visibility="collapsed")

    # Apply filters
    filtered = ps_df.copy()
    if "All" not in pos_filter and pos_filter:
        allowed_positions = [p for g in pos_filter for p in POSITION_GROUPS.get(g, [])]
        filtered = filtered[filtered["position"].isin(allowed_positions)]
    if comp_filter != "All":
        filtered = filtered[filtered["competition"] == comp_filter]
    if team_filter != "All":
        filtered = filtered[filtered["team"] == team_filter]
    filtered = filtered[filtered["minutes_played"] >= min_mins]

    if filtered.empty:
        st.warning("No players match the current filters. Try relaxing the criteria.")
        return

    # ── Player selector ───────────────────────────────────────────────────────
    player_options = sorted(filtered["display_name"].unique())
    st.markdown('<p class="cv-label" style="margin-top:0.6rem;">Select Player</p>',
                unsafe_allow_html=True)
    selected_name = st.selectbox("player_select", player_options,
                                  label_visibility="collapsed")

    player_rows = filtered[filtered["display_name"] == selected_name]
    # Aggregate if multiple seasons
    if len(player_rows) > 1:
        player_row = player_rows.sort_values("minutes_played", ascending=False).iloc[0]
    else:
        player_row = player_rows.iloc[0]

    pid = player_row["player_id"]

    # Get per90 row
    pp_rows = pp_df[pp_df["player_id"] == pid]
    if pp_rows.empty:
        pp_rows = pp_df[pp_df["display_name"] == selected_name]
    per90_row = pp_rows.sort_values("minutes_played", ascending=False).iloc[0] \
                if not pp_rows.empty else pd.Series(dtype=float)

    # Get cluster row
    cl_rows = cl_df[cl_df["player_id"] == pid]
    cluster_row = cl_rows.iloc[0] if not cl_rows.empty else None

    st.markdown("<br>", unsafe_allow_html=True)
    render_player_profile(player_row, per90_row, cluster_row, pp_df)


# ─────────────────────────────────────────────────────────────────────────────
# PAGE 2 — PLAYER COMPARISON
# ─────────────────────────────────────────────────────────────────────────────
def page_player_comparison(ps_df, pp_df, cl_df):
    cv_section("⚖️ Player Comparison",
               "Side-by-side analysis of two players using per-90 percentile metrics, radar charts, and statistical tables")
    st.markdown('<hr style="border-color:#1e3050;">', unsafe_allow_html=True)

    all_names = sorted(pp_df[pp_df["minutes_played"] >= MIN_MINUTES]["display_name"].unique())

    c1, _, c2 = st.columns([5, 1, 5])
    with c1:
        st.markdown('<p class="cv-label">Player 1</p>', unsafe_allow_html=True)
        p1_name = st.selectbox("p1", all_names,
                                index=all_names.index("Lionel Andrés Messi Cuccittini")
                                      if "Lionel Andrés Messi Cuccittini" in all_names else 0,
                                label_visibility="collapsed", key="cp1")
    with _:
        st.markdown("<br><br>", unsafe_allow_html=True)
        st.markdown('<div style="text-align:center;font-family:\'Barlow Condensed\',sans-serif;'
                    'font-size:1.6rem;color:#5a7a9a;">VS</div>', unsafe_allow_html=True)
    with c2:
        st.markdown('<p class="cv-label">Player 2</p>', unsafe_allow_html=True)
        p2_default = all_names.index("Kylian Mbappé Lottin") \
                     if "Kylian Mbappé Lottin" in all_names else 1
        p2_name = st.selectbox("p2", all_names, index=p2_default,
                                label_visibility="collapsed", key="cp2")

    if p1_name == p2_name:
        st.warning("Please select two different players.")
        return

    def get_pp_row(name):
        rows = pp_df[pp_df["display_name"] == name]
        return rows.sort_values("minutes_played", ascending=False).iloc[0] \
               if not rows.empty else pd.Series(dtype=float)

    def get_ps_row(name):
        rows = ps_df[ps_df["display_name"] == name]
        return rows.sort_values("minutes_played", ascending=False).iloc[0] \
               if not rows.empty else pd.Series(dtype=float)

    p1_pp = get_pp_row(p1_name); p2_pp = get_pp_row(p2_name)
    p1_ps = get_ps_row(p1_name); p2_ps = get_ps_row(p2_name)

    st.markdown('<hr style="border-color:#1e3050;">', unsafe_allow_html=True)

    # ── Quick stat cards ──────────────────────────────────────────────────────
    mc1, mc2 = st.columns(2)
    for col, ps_row, pp_row, color in [(mc1, p1_ps, p1_pp, COLORS["green"]),
                                        (mc2, p2_ps, p2_pp, COLORS["accent"])]:
        with col:
            name = ps_row.get("display_name", "—")
            team = ps_row.get("team", "—")
            pos  = ps_row.get("position", "—")
            cl_rows = cl_df[cl_df["player_id"] == ps_row.get("player_id", -1)]
            cid = int(cl_rows.iloc[0]["cluster"]) if not cl_rows.empty else -1
            arch = CLUSTER_ARCHETYPES.get(cid, {})
            st.markdown(f"""
            <div class="cv-card" style="border-left:4px solid {color};">
                <div style="font-family:'Barlow Condensed',sans-serif;font-size:1.5rem;
                     font-weight:800;color:{color};">{name}</div>
                <div style="font-size:0.82rem;color:{COLORS['muted']};margin-bottom:0.8rem;">
                    {team} · {pos}</div>
                <div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;font-size:0.85rem;">
                    <div>Goals: <b style="color:{COLORS['text']};">{_fmt(ps_row.get('goals',0),0)}</b></div>
                    <div>Assists: <b style="color:{COLORS['text']};">{_fmt(ps_row.get('assists',0),0)}</b></div>
                    <div>xG: <b style="color:{COLORS['text']};">{_fmt(ps_row.get('xg',0))}</b></div>
                    <div>Minutes: <b style="color:{COLORS['text']};">{_fmt(ps_row.get('minutes_played',0),0)}</b></div>
                </div>
                <div style="margin-top:0.6rem;">
                    <span class="archetype-chip" style="background:rgba(255,255,255,0.06);
                          color:{arch.get('color',color)};border:1px solid {arch.get('color',color)};">
                          {arch.get('icon','⚽')} {arch.get('name','—')}</span>
                </div>
            </div>""", unsafe_allow_html=True)

    # ── Visualization tabs ────────────────────────────────────────────────────
    st.markdown("<br>", unsafe_allow_html=True)
    t1, t2, t3 = st.tabs(["🕸️ Radar Comparison", "📊 Percentile Bars", "📋 Stats Table"])

    with t1:
        st.plotly_chart(
            make_radar(p1_pp, p2_pp, p1_name, p2_name, pp_df),
            use_container_width=True, config={"displayModeBar": False})

    with t2:
        st.plotly_chart(
            make_comparison_bar(p1_pp, p2_pp, p1_name, p2_name, pp_df),
            use_container_width=True, config={"displayModeBar": False})

    with t3:
        _render_stats_table(p1_ps, p2_ps, p1_pp, p2_pp, p1_name, p2_name, pp_df)


def _render_stats_table(p1_ps, p2_ps, p1_pp, p2_pp, p1_name, p2_name, pp_df):
    """Side-by-side stats table with winner highlighting."""
    metrics = [
        ("Goals", "goals", False), ("Assists", "assists", False),
        ("xG", "xg", False), ("xA", "xassists", False),
        ("Goals/90", "goals_per90", True), ("Assists/90", "assists_per90", True),
        ("xG/90", "xg_per90", True), ("Progressive Passes", "progressive_passes", False),
        ("Pass Accuracy %", "pass_accuracy", False),
        ("Dribbles Completed", "dribbles_completed", False),
        ("Tackles", "tackles", False), ("Interceptions", "interceptions", False),
        ("Pressures/90", "pressures_per90", True),
        ("Aerial Success %", "aerial_success_rate", False),
    ]
    rows = []
    for label, col, per90 in metrics:
        src1 = p1_pp if per90 else p1_ps
        src2 = p2_pp if per90 else p2_ps
        v1 = src1.get(col, np.nan); v2 = src2.get(col, np.nan)
        if pd.isna(v1) and pd.isna(v2): continue
        rows.append({"Metric": label,
                     p1_name: round(float(v1), 2) if not pd.isna(v1) else "—",
                     p2_name: round(float(v2), 2) if not pd.isna(v2) else "—"})
    if rows:
        tbl = pd.DataFrame(rows)
        st.dataframe(tbl.style.apply(
            lambda row: [
                "", 
                "background-color: rgba(0,255,157,0.12); color: #00ff9d;" if (
                    isinstance(row[p1_name], (int, float)) and
                    isinstance(row[p2_name], (int, float)) and
                    row[p1_name] > row[p2_name]) else "",
                "background-color: rgba(0,212,255,0.12); color: #00d4ff;" if (
                    isinstance(row[p1_name], (int, float)) and
                    isinstance(row[p2_name], (int, float)) and
                    row[p2_name] > row[p1_name]) else "",
            ], axis=1
        ), use_container_width=True, height=480)


# ─────────────────────────────────────────────────────────────────────────────
# PAGE 3 — CLUSTER EXPLORER
# ─────────────────────────────────────────────────────────────────────────────
def page_cluster_explorer(ps_df, cl_df, sim_df):
    cv_section("🗺️ Cluster Explorer",
               "KMeans-driven player archetypes visualised in PCA and t-SNE space — discover how players are grouped by playing style")
    st.markdown('<hr style="border-color:#1e3050;">', unsafe_allow_html=True)

    # Merge cluster data with basic stats
    merged = cl_df.merge(
        ps_df[["player_id","team","competition","minutes_played",
               "goals","assists","position"]].drop_duplicates("player_id"),
        on="player_id", how="left"
    )

    # ── Overview metrics ──────────────────────────────────────────────────────
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Total Players Clustered", f"{len(cl_df):,}")
    m2.metric("Archetypes Discovered",   "8")
    m3.metric("Largest Cluster",
              CLUSTER_ARCHETYPES[int(cl_df["cluster"].value_counts().idxmax())]["name"])
    m4.metric("Competitions Covered",    ps_df["competition"].nunique())

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Archetype size chart ──────────────────────────────────────────────────
    st.plotly_chart(make_cluster_size_bar(cl_df),
                    use_container_width=True, config={"displayModeBar": False})

    st.markdown('<hr style="border-color:#1e3050;">', unsafe_allow_html=True)

    # ── Player highlight selector ─────────────────────────────────────────────
    c1, c2, c3 = st.columns([3, 2, 2])
    with c1:
        st.markdown('<p class="cv-label">Highlight a Player</p>', unsafe_allow_html=True)
        all_cluster_names = sorted(merged["player_name"].dropna().unique())
        highlight_name = st.selectbox("hl", ["— None —"] + all_cluster_names,
                                       label_visibility="collapsed")
    with c2:
        st.markdown('<p class="cv-label">Filter Archetype</p>', unsafe_allow_html=True)
        arch_filter = st.selectbox("af", ["All"] + [a["name"] for a in CLUSTER_ARCHETYPES.values()],
                                    label_visibility="collapsed")
    with c3:
        st.markdown('<p class="cv-label">Projection Method</p>', unsafe_allow_html=True)
        proj_mode = st.radio("proj", ["PCA", "t-SNE"], horizontal=True,
                              label_visibility="collapsed")

    highlight_id = None
    if highlight_name != "— None —":
        rows = cl_df[cl_df["player_name"] == highlight_name]
        if not rows.empty:
            highlight_id = int(rows.iloc[0]["player_id"])

    # Filter by archetype
    plot_df = cl_df.copy()
    if arch_filter != "All":
        cid = next((k for k, v in CLUSTER_ARCHETYPES.items() if v["name"] == arch_filter), None)
        if cid is not None:
            plot_df = plot_df[plot_df["cluster"] == cid]

    # ── Scatter plot ──────────────────────────────────────────────────────────
    st.plotly_chart(
        make_cluster_scatter(plot_df, highlight_id, mode=proj_mode.lower().replace("-","").replace(" ","")),
        use_container_width=True, config={"displayModeBar": False})

    # ── Archetype description cards ───────────────────────────────────────────
    st.markdown('<hr style="border-color:#1e3050;">', unsafe_allow_html=True)
    st.markdown('<div class="cv-subheading">Archetype Descriptions</div>', unsafe_allow_html=True)

    rows_arch = [list(CLUSTER_ARCHETYPES.items())[i:i+4]
                 for i in range(0, 8, 4)]
    for row in rows_arch:
        cols = st.columns(4)
        for col, (cid, arch) in zip(cols, row):
            count = len(cl_df[cl_df["cluster"] == cid])
            with col:
                st.markdown(f"""
                <div class="cv-card" style="border-top:3px solid {arch['color']};min-height:160px;">
                    <div style="font-size:1.6rem;margin-bottom:4px;">{arch['icon']}</div>
                    <div style="font-family:'Barlow Condensed',sans-serif;font-size:1rem;
                         font-weight:700;color:{arch['color']};letter-spacing:0.5px;
                         margin-bottom:6px;">{arch['name']}</div>
                    <div style="font-size:0.78rem;color:{COLORS['muted']};
                         margin-bottom:8px;">{count} players</div>
                    <div style="font-size:0.82rem;color:{COLORS['text']};
                         line-height:1.5;">{arch['desc']}</div>
                </div>""", unsafe_allow_html=True)

    # ── Top players per highlighted archetype ─────────────────────────────────
    if arch_filter != "All":
        cid = next((k for k, v in CLUSTER_ARCHETYPES.items() if v["name"] == arch_filter), None)
        if cid is not None:
            st.markdown("<br>", unsafe_allow_html=True)
            st.markdown(f'<div class="cv-subheading">Top Players — {arch_filter}</div>',
                        unsafe_allow_html=True)
            cluster_pids = cl_df[cl_df["cluster"] == cid]["player_id"].tolist()
            top_players = ps_df[ps_df["player_id"].isin(cluster_pids)]\
                          .sort_values("minutes_played", ascending=False)\
                          .head(15)[["display_name","team","competition","position",
                                     "goals","assists","minutes_played"]]
            st.dataframe(top_players.reset_index(drop=True), use_container_width=True, height=400)


# ─────────────────────────────────────────────────────────────────────────────
# PAGE 4 — SIMILARITY ENGINE
# ─────────────────────────────────────────────────────────────────────────────
def page_similarity_engine(ps_df, pp_df, sim_df, cl_df):
    cv_section("🔗 Similarity Engine",
               "Find players with identical playing styles using cosine similarity on 24 scaled performance features")
    st.markdown('<hr style="border-color:#1e3050;">', unsafe_allow_html=True)

    # ── Controls ──────────────────────────────────────────────────────────────
    c1, c2, c3 = st.columns([4, 2, 2])
    with c1:
        st.markdown('<p class="cv-label">Reference Player</p>', unsafe_allow_html=True)
        query_names = sorted(sim_df["player_name"].unique())
        query_name  = st.selectbox("sim_q", query_names,
                                    index=query_names.index("Lionel Andrés Messi Cuccittini")
                                          if "Lionel Andrés Messi Cuccittini" in query_names else 0,
                                    label_visibility="collapsed")
    with c2:
        st.markdown('<p class="cv-label">Results Count</p>', unsafe_allow_html=True)
        n_results = st.slider("n_sim", 5, 20, 10, label_visibility="collapsed")
    with c3:
        st.markdown('<p class="cv-label">Same Position Only</p>', unsafe_allow_html=True)
        same_pos = st.toggle("Same Position", value=False)

    query_rows = sim_df[sim_df["player_name"] == query_name]
    if query_rows.empty:
        st.error("Player not found in similarity dataset.")
        return

    query_row = query_rows.iloc[0]
    query_pid = int(query_row["player_id"])

    with st.spinner("Computing cosine similarity across all players…"):
        similar = find_similar_players(query_pid, sim_df, n=n_results, same_pos_only=same_pos)

    st.markdown('<hr style="border-color:#1e3050;">', unsafe_allow_html=True)

    # ── Reference player card ─────────────────────────────────────────────────
    ps_row = ps_df[ps_df["player_id"] == query_pid]
    if not ps_row.empty:
        ps_row = ps_row.sort_values("minutes_played", ascending=False).iloc[0]
        cl_row = cl_df[cl_df["player_id"] == query_pid]
        arch = CLUSTER_ARCHETYPES.get(int(cl_row.iloc[0]["cluster"]), {}) \
               if not cl_row.empty else {}

        st.markdown(f"""
        <div class="player-badge">
            <div class="cv-label">🎯 Reference Player</div>
            <div class="player-name">{query_name}</div>
            <div class="player-sub">
                🏟️ <b>{ps_row['team']}</b> · {ps_row['position']} · 🏆 {ps_row['competition']}
                &nbsp;&nbsp;
                <span class="archetype-chip" style="background:rgba(255,255,255,0.07);
                    color:{arch.get('color', COLORS['accent'])};
                    border:1px solid {arch.get('color', COLORS['accent'])};">
                    {arch.get('icon','⚽')} {arch.get('name','—')}</span>
            </div>
        </div>""", unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Similar players grid ──────────────────────────────────────────────────
    st.markdown('<div class="cv-subheading">Most Similar Players</div>', unsafe_allow_html=True)

    for i in range(0, len(similar), 2):
        cols = st.columns(2)
        for j, col in enumerate(cols):
            idx = i + j
            if idx >= len(similar): break
            sim_row = similar.iloc[idx]
            sim_score = sim_row["similarity"]
            score_pct = int(sim_score * 100)
            score_color = (COLORS["green"] if score_pct >= 90 else
                           COLORS["accent"] if score_pct >= 75 else
                           COLORS["gold"])

            # Get archetype
            cl_rows = cl_df[cl_df["player_id"] == sim_row["player_id"]]
            arch = CLUSTER_ARCHETYPES.get(int(cl_rows.iloc[0]["cluster"]), {}) \
                   if not cl_rows.empty else {}

            with col:
                st.markdown(f"""
                <div class="cv-card" style="border-left:3px solid {score_color};">
                    <div style="display:flex;justify-content:space-between;align-items:flex-start;">
                        <div>
                            <div style="font-family:'Barlow Condensed',sans-serif;font-size:1.15rem;
                                 font-weight:700;color:{COLORS['text']};">
                                #{idx+1} &nbsp; {sim_row['player_name']}</div>
                            <div style="font-size:0.8rem;color:{COLORS['muted']};margin-top:2px;">
                                {sim_row['primary_position']} · {sim_row['team_name']}</div>
                            <div style="font-size:0.78rem;color:{COLORS['muted']};">
                                {sim_row['competition_name']}</div>
                        </div>
                        <div style="text-align:right;flex-shrink:0;margin-left:12px;">
                            <div style="font-family:'Barlow Condensed',sans-serif;
                                 font-size:1.8rem;font-weight:900;color:{score_color};">
                                 {score_pct}%</div>
                            <div style="font-size:0.7rem;color:{COLORS['muted']};">SIMILARITY</div>
                        </div>
                    </div>
                    <div style="margin-top:8px;">
                        <div style="background:#1e3050;border-radius:4px;height:6px;">
                            <div style="width:{score_pct}%;height:6px;border-radius:4px;
                                 background:{score_color};"></div>
                        </div>
                    </div>
                    <div style="margin-top:6px;">
                        <span class="archetype-chip" style="font-size:0.75rem;padding:3px 10px;
                            background:rgba(255,255,255,0.05);color:{arch.get('color',COLORS['muted'])};
                            border:1px solid {arch.get('color',COLORS['border'])};">
                            {arch.get('icon','⚽')} {arch.get('name','—')}</span>
                    </div>
                </div>""", unsafe_allow_html=True)

    # ── Similarity heatmap among top 8 ───────────────────────────────────────
    st.markdown('<hr style="border-color:#1e3050;">', unsafe_allow_html=True)
    st.markdown('<div class="cv-subheading">Similarity Heatmap — Reference vs Top Matches</div>',
                unsafe_allow_html=True)

    top8_ids = [query_pid] + similar["player_id"].head(7).tolist()
    top8_df  = sim_df[sim_df["player_id"].isin(top8_ids)].drop_duplicates("player_id")
    top8_df  = top8_df.set_index("player_id").loc[[i for i in top8_ids if i in top8_df.index]]

    X_top8 = top8_df[FEATURE_COLS_SIM].fillna(0).values
    sim_matrix = cosine_similarity(X_top8)
    names = top8_df["player_name"].tolist()

    st.plotly_chart(make_similarity_heatmap(sim_matrix, names),
                    use_container_width=True, config={"displayModeBar": False})

    # ── Feature comparison breakdown ──────────────────────────────────────────
    with st.expander("🔬 Feature-level Similarity Breakdown"):
        top3_ids = similar["player_id"].head(3).tolist()
        comp_df  = sim_df[sim_df["player_id"].isin([query_pid] + top3_ids)].drop_duplicates("player_id")
        comp_display = comp_df[["player_name"] + FEATURE_COLS_SIM].set_index("player_name")
        st.dataframe(comp_display.T.style.background_gradient(cmap="Blues", axis=1),
                     use_container_width=True, height=520)


# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────
def main():
    with st.spinner("Loading player intelligence data…"):
        ps_df  = load_player_stats()
        pp_df  = load_player_per90()
        sim_df = load_similarity_features()
        cl_df  = load_clustered_features()

    page = render_sidebar()

    if page == "Player Search & Profile":
        page_player_profile(ps_df, pp_df, sim_df, cl_df)
    elif page == "Player Comparison":
        page_player_comparison(ps_df, pp_df, cl_df)
    elif page == "Cluster Explorer":
        page_cluster_explorer(ps_df, cl_df, sim_df)
    elif page == "Similarity Engine":
        page_similarity_engine(ps_df, pp_df, sim_df, cl_df)


if __name__ == "__main__":
    main()
